language: python
python:
    - "3.5"

services:
  - redis-server

install: pip install -r requirements.txt
script: cd src;python -m unittest
deploy: docker build . -t bedekelly/chatbox && docker push bedekelly/chatbox
